### ISSUE TITLE
Update to monaco-editor 0.11.1

### ISSUE THREAD

**Issue by TedDriggs** [superRaytin/react-monaco-editor#101]
Earlier today, monaco released an update.

**Comment by domoritz** [comment]
Excellent. Can you send a PR?

**Comment by domoritz** [comment]
Oh sweet: "ESM distribution (compatible with e.g. webpack)." This will make deployment so much easier. We probably need to do some cleanup here, though.

**Comment by TedDriggs** [comment]
> Can you send a PR?

I'm traveling pretty frequently the next couple of weeks, so I don't know when I'll have time. I took a stab at it this afternoon, but got errors from the example when I tried to build and haven't had time to dig deeper.

**Comment by domoritz** [comment]
I'm quite busy for the next few weeks as well. If anyone is reading this and wants to use the latest Monaco, I'd love to see a PR. Otherwise, we'll update in a few weeks.

**Comment by TedDriggs** [comment]
@domoritz I've gotten the build working, and I just tried blindly updating the dependency in the examples and the main package and it _seems_ to be working. Do you consider the refactor a mandatory part of this update?

**Comment by domoritz** [comment]
Details about ESM: https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md#0110-14032018 and https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md. I can look at this after next week.
