### ISSUE TITLE
CI via TravisCI?

### ISSUE THREAD

**Issue by blaskovicz** [superRaytin/react-monaco-editor#105]
Somehow, with my previous commit in #104, eslint didn't get triggered correctly, which is now causing my build to fail. To prevent this in the future, we should set up CI to run on a pull requests and configure the repo to wait for TravisCI commit sign off.

This will also allow TravisCI to run a publish on tag push (rather than doing it manually), if desired. I'm happy to help maintain that, if you'd like to add me to.

I added my own `.travis.yml` that we can use as a starter and fixed the aforementioned lint issue.

https://travis-ci.org/blaskovicz/react-monaco-editor

I'll open my pull request momentarily...

**Comment by blaskovicz** [comment]
@domoritz can you tag 0.14.1 as a bugfix release wrt the width/height?

**Comment by domoritz** [comment]
Done
