### ISSUE TITLE
Support ESM

### ISSUE THREAD

**Issue by domoritz** [superRaytin/react-monaco-editor#108]
Details about ESM: https://github.com/Microsoft/monaco-editor/blob/master/CHANGELOG.md#0110-14032018 and https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md. 

See #107 and #101

**Comment by LucienLee** [comment]
For reference: Bundle with webpack plugin https://github.com/Microsoft/monaco-editor/pull/767

**Comment by c9s** [comment]
+1

**Comment by domoritz** [comment]
If somebody wants to send a PR, that would be lovely.

**Comment by marbemac** [comment]
And that webpack plugin has now been published! https://github.com/Microsoft/monaco-editor-webpack-plugin

**Comment by domoritz** [comment]
Awesome, I'm excited to have a cleaner react package.
