### ISSUE TITLE
how to get the selected text ?

### ISSUE THREAD

**Issue by aiic03** [superRaytin/react-monaco-editor#112]
According to https://github.com/Microsoft/monaco-editor/issues/639

We can get selected text using following code:

```
window.editor.getModel().getValueInRange(window.editor.getSelection())
```

But in this react version here, the `editor` reference is a `ProxyComponent`.

```
<MonacoEditor
          ref={(editor) => {
            this.editor = editor; // keep the reference here.
          }}
          className={styles.editor}
          width={1008}
          height={664}
          automaticLayout
          language="sql"
          theme="vs" // vs, vs-dark, hc-black
          value="!-- type your code here..."
          options={options}
          onChange={::this.onChange}
          editorDidMount={::this.editorDidMount}
        />
```

![image](https://user-images.githubusercontent.com/11695765/38978959-7cfeac00-43eb-11e8-89a2-358dd34bfc10.png)

How do I call `editor.getModel().getValueInRange(window.editor.getSelection())` ?

**Comment by domoritz** [comment]
Can you look in the code and send a PR to expose the editor? `editorDidMount` get's the editor.

**Comment by aiic03** [comment]
Well, actually, storing the reference from `editorDidMount`  by the following code can be a way:
```
  editorDidMount(editor, monaco) {
    this.setState({
      editor: editor
  });

...
// pass editor reference via state
var selection = this.state.editor.getModel().getValueInRange(this.state.editor.getSelection());
```

it works, thanks for the reply.

**Comment by gawarivivek** [comment]
![image](https://user-images.githubusercontent.com/8142506/175042567-cf2e877e-6371-457c-ba1e-6647fc84ffda.png)

![image](https://user-images.githubusercontent.com/8142506/175042712-f857015b-e287-4ef2-a856-57f539b09e51.png)

using ngx-monaco-diff-editor wants to recived highlighted text (GOA and US )but couldnt get its tried a lot 
diffEditor.getModel().modified.getValue(); -- throgh this i am getting entire text 
tried these many ways 
![image](https://user-images.githubusercontent.com/8142506/175043507-4a697bd5-1642-40ae-bff0-c7827be8d3d7.png)

please help me out 
thank you so much
