### ISSUE TITLE
monaco-editor version not latest

### ISSUE THREAD

**Issue by shallwefootball** [superRaytin/react-monaco-editor#113]
when i install react-monaco-editor,

`monaco-editor` version is 

```
  "monaco-editor": "^0.10.0",
```

in `/node_modules/react-monaco-editor/package.json`.

why??

**Comment by domoritz** [comment]
Because pre 1.0 versions may break compatibility with minor versions as well. We have to test very version. Can you send a pull request to update to the latest version?

**Comment by domoritz** [comment]
Actually, https://github.com/superRaytin/react-monaco-editor/pull/111/files will fix this. I just need to resolve one issue with webpack.

**Comment by domoritz** [comment]
Fixed
