### ISSUE TITLE
TypeScript Definitions

### ISSUE THREAD

**Issue by nikeee** [superRaytin/react-monaco-editor#114]
Is there any support planned to ship some type definitions along with the npm package? The definitions of Monaco itself could just get re-exported, I think. However, it would be nice to have the component typed aswell.

**Comment by nikeee** [comment]
I'll see what I can do!

**Comment by nikeee** [comment]
I made a PR with some basic types. However, I'm not sure about the nullability/undefinability of som parameters and fields. Also, there might be methods which are actually part of the private API, so we could remove them.

**Comment by expobrain** [comment]
Thank you @nikeee!

I'm not an expert about Typescript but this PR can be uses as a starting point for everyone else to improve the definitions.
