### ISSUE TITLE
`example` directory was published to npm

### ISSUE THREAD

**Issue by VincentBel** [superRaytin/react-monaco-editor#119]
The large `node_modules` in `example` directory was published to npm:
<https://unpkg.com/react-monaco-editor@0.16.0/example/node_modules/>

---

In `.npmignore` file, we ignore `examples` directory, rather than `example` 😆:

https://github.com/superRaytin/react-monaco-editor/blob/2ad095ff1aee25d1083a3767db29d31b74aebf2b/.npmignore#L1

I suggest use the [`files` field in `package.json`](https://docs.npmjs.com/files/package.json#files) to whitelist published files rather than blacklist them.

**Comment by domoritz** [comment]
Thanks for sending the issue!
