### ISSUE TITLE
`@types/react` version should match `react` version in peerDependencies

### ISSUE THREAD

**Issue by VincentBel** [superRaytin/react-monaco-editor#121]
Currently, `react-monaco-editor` requires the version of `@types/react` to be higher than `16.3.4`.

https://github.com/superRaytin/react-monaco-editor/blob/ab2acfede17fac6641dbfbdf7155cedc16de9f76/package.json#L61-L65

When I install it, I'll install two `@types/react` package in my project(another one required by other packages), which result with a typing error.

![image](https://user-images.githubusercontent.com/6076919/40173532-ba6ffe0c-5a04-11e8-8b21-e42329aed263.png)

I think the required version of `@types/react` should also be `^15.x || ^16.x`. Or just use `*` like how most DefinitelyTyped packages do([`react-dom`](https://unpkg.com/@types/react-dom@16.0.5/package.json), [`react-router`](https://unpkg.com/@types/react-router@4.0.25/package.json)).

**Comment by domoritz** [comment]
Can you send a PR?

**Comment by OneCyrus** [comment]
yes, same issue here. changing to * would be great.

**Comment by domoritz** [comment]
Done
