### ISSUE TITLE
Usage with TypeScript + Webpack

### ISSUE THREAD

**Issue by nikeee** [superRaytin/react-monaco-editor#128]
I've create a minimal reproduction of my problem: https://github.com/nikeee/react-monaco-editor-typescript-repro

If I run `webpack --mode production` or `webpack --mode development` (doesn't matter), I get this error on compilation several times (with different file names):
```
ERROR in ./node_modules/monaco-editor/esm/vs/editor/contrib/zoneWidget/zoneWidget.css
Module build failed: Unknown word (2:1)

  1 |
> 2 | var content = require("!!./zoneWidget.css");
    | ^
  3 |
  4 | if(typeof content === 'string') content = [[module.id, content, '']];
  5 |

 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/zoneWidget/zoneWidget.js 6:0-26
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/referenceSearch/peekViewWidget.js
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/referenceSearch/referencesWidget.js
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/referenceSearch/referencesController.js
 @ ./node_modules/monaco-editor/esm/vs/editor/standalone/browser/referenceSearch/standaloneReferenceSearch.js
 @ include-loader!./node_modules/monaco-editor/esm/vs/editor/editor.main.js
 @ ./node_modules/react-monaco-editor/lib/diff.js
 @ ./node_modules/react-monaco-editor/lib/index.js
 @ ./src/index.tsx
```

It seems to me that something does not process CSS as it should. I've set up a CSS loader (see `webpack-config.js`), but I'm not into frontend toolchains that much, so I actually don't really know why this error occurs.

Once I used the `CopyWebpackPlugin` when I was testing if the things that I want to do would work. Now, using `MonacoWebpackPlugin` it does not seem to work (any more?). The build now fails and basically emits non-working JS (if any).

What am I missing here?

**Comment by domoritz** [comment]
Hmm, you probably need some kind of style loader. https://github.com/vega/editor used typescript and webpack with react monaco. Maybe you can copy from there.

**Comment by nikeee** [comment]
Apparently, the css loaders were in the wrong order. [This commit](https://github.com/nikeee/react-monaco-editor-typescript-repro/commit/5a6ebe90520aece3c79fe823ae3234ea19b0fed5) fixed it FYI.

**Comment by domoritz** [comment]
😞
