### ISSUE TITLE
Peer Dependency?

### ISSUE THREAD

**Issue by nikeee** [superRaytin/react-monaco-editor#130]
I've read these issues: #45 and #52.

Is there any chance that monaco-editor will be a peer-dependency again? I have another dependency that requires a different monaco version.

**Comment by domoritz** [comment]
We could make the monaco version `0.13 || 0.14` to allow this. I don't want to deal with different version too much, though. It's hard enough to keep things working and there is no way we can test against all different version of monaco.

**Comment by domoritz** [comment]
I didn't mean to use these specific versions but show the pattern. You are right that the problem is that the API may change and so I'd prefer not to support version ranges and instead ask people to install an old version of react monaco if they want to use a different version of monaco.
