### ISSUE TITLE
Broken with webpack -- Error: Cannot find module "."

### ISSUE THREAD

**Issue by jeff3dx** [superRaytin/react-monaco-editor#137]
As you may know, monaco-editor is broken on webpack projects.  It appears fine at first, but behind the scenes it fails to load webworker modules for language parsing, autocomplete, etc.  There are [various workarounds published around the web](https://github.com/Microsoft/monaco-editor/issues/933).  When I found this "react" wrapper for monaco-editor I assumed it would include a fix for it but it does not. As with monaco-editor, react-monaco-editor is broken on webpack. Wrapping monaco-editor in a react component has some value, but the real value would be in having it non-broken with webpack projects, which today is just about everyone.

**Comment by domoritz** [comment]
This module can't do anything about it. Have you tried to use the Monaco webpack plugin from microsoft?

**Comment by AlexandritT** [comment]
I have same problem. And it is not only on this module, but on the clear monaco too. I've tried to use monaco-webpack plugin, but it caused much more problems like this:
```
ERROR in ./js/index.js
Module parse failed: Unexpected token (14:4)
You may need an appropriate loader to handle this file type.
| // For more details see: https://facebook.github.io/react/docs/top-level-api.html#react.render
| render(
|     <AppContext.Provider value={{ appName: "My First Frontbench App!" }}>
|         <Main />
|     </AppContext.Provider>
 @ multi (webpack)-dev-server/client?http://localhost:8888 ./js/index.js
```

**Comment by eryshev** [comment]
I've added Monaco Webpack  plugin to my create-react-app and it solved the problem.

**Comment by rizkyramadhan** [comment]
Hi, how do you add webpack plugin to create-react-app without injecting ?

**Comment by eryshev** [comment]
@rizkyramadhan I didn't, I've heard that it's possible but I didn't find how so I ejected 😕

**Comment by domoritz** [comment]
I'm going to close this issue since there isn't much we can do in the react wrapper. Feel free to comment with solutions.
