### ISSUE TITLE
Disable Editing

### ISSUE THREAD

**Issue by logeshpaul** [superRaytin/react-monaco-editor#141]
I have a requirement where the user without proper privileges will be able to only "View" the file but not able to edit them. Is there an `option` which I can pass to do that?

**Comment by domoritz** [comment]
Yes, you can set the editor to read-only. Check vega/editor for an example.

**Comment by logeshpaul** [comment]
@domoritz Thanks

**Comment by sulenchy** [comment]
Thanks @domoritz
