### ISSUE TITLE
Use 'monaco-editor/esm/vs/editor/editor.api' in monaco import

### ISSUE THREAD

**Issue by panjiesw** [superRaytin/react-monaco-editor#142]
Even if I use [Monaco Webpack Plugin](https://github.com/Microsoft/monaco-editor-webpack-plugin) as advised in README, I still get a bunch of other features/language I don't specify in the plugin.

This is because `react-monaco-editor` import them like this:

```javascript
import * as monaco from 'monaco-editor';
```

instead of

```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
```

**Comment by leachiM2k** [comment]
Hello,
we are also struggling with the unnecessary heavy monaco editor installation. We don't need no language support, because we introduce our own language. Using the webpack plugin we could save a lot of space and parsing time.

What is the opinion about this issue?
Do you need a PR for this?

**Comment by panjiesw** [comment]
Other possible solution is to pass `monaco` into the component props. So this component doesn't need to import `monaco-editor` and leave the user flexibility of how to import the editor.

```javascript
// in editor.js

// instead of
this.editor = monaco.editor.create(...) // monaco is imported by editor.js
// it can be
this.editor = this.props.monaco.editor.create(...) // monaco comes from user

// Add it to propTypes
MonacoEditor.propTypes = {
  //...
  monaco: PropTypes.object.isRequired
}
```

And consumer of this component can use it like this

```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
// or
import * as monaco from 'monaco-editor';
// or even dynamic import

import MonacoEditor from 'react-monaco-editor';

// use it
<MonacoEditor
  monaco={monaco}
  width="800"
  height="600"
  language="javascript"
  theme="vs-dark"
  value={code}
  options={options}
  onChange={::this.onChange}
  editorDidMount={::this.editorDidMount}
/>
```
