### ISSUE TITLE
MonacoDiffEditor shows an empty page with a close button

### ISSUE THREAD

**Issue by sillinbaby** [superRaytin/react-monaco-editor#145]
MonacoDiffEditor shows an empty page every time and the 'real' diff editor will show only after click the close button. How to remove this empty page? Thanks
<img width="1280" alt="screen shot 2018-09-07 at 12 42 52 pm" src="https://user-images.githubusercontent.com/40295089/45198912-a30ccc00-b29b-11e8-917d-770ae44b5526.png">

**Comment by domoritz** [comment]
How do you preproduce this error? Is this with the demo in this repo?

**Comment by sillinbaby** [comment]
No, I don't use the demo in the this repo. In my user case, I add <div> outside the MonacoDiffEditor. There is style to control whether to show div or hide it.  If I remove the div, everything works fine.
`
import styled from "styled-components";
const EditorContainer = styled.div
  position: absolute;
  top: 48px;
  left: 0;
  height: 100%;
  width: 100%;
  z-index: 1001;


 render() {
    let showEditorStyle = this.props.visible ? {display : "flex"} : {display: "none"}
    return (
      <EditorContainer style = {showEditorStyle as any}>
        <MonacoDiffEditor
          theme="vs-dark"
          language="json"
          original={code1}
          value={code2}
          options={{selectOnLineNumbers: true}}
          editorDidMount={editorDidMount}
          editorWillMount={editorWillMount}
        />
     </EditorContainer>
    );
  }
`

**Comment by domoritz** [comment]
The error seems unrelated to the editor component then.
