### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by ktalebian** [superRaytin/react-monaco-editor#147]
As soon as I `push` `new MonacoWebpackPlugin()` to my existing webpack, my webpack fails with

```
Module parse failed: /path/to/ts/file.tds Unexpected token (8:8)
You may need an appropriate loader to handle this file type.
| render(Root);
| 
| declare const module;
| if (module.hot) {
|       module.hot.accept('./root', () => {
 @ multi (webpack)-dev-server/client?http://localhost:3020 webpack/hot/dev-server webpack-dev-server/client?http://localhost:3020 webpack/hot/only-dev-server ./src/ts/index.tsx
```

I'm running webpack v3.5.1. Help is appreciated.

**Comment by domoritz** [comment]
Do you get it with the example in this repo?

**Comment by ktalebian** [comment]
No, this is adding this to my existing service.

**Comment by domoritz** [comment]
Unfortunately, I can't help in this case. Maybe someone else can help. I'm going to close this issue since there is no immediate action item but feel free to add comments below.
