### ISSUE TITLE
react and react-dom should not be dependencies

### ISSUE THREAD

**Issue by leMaik** [superRaytin/react-monaco-editor#15]
This is a really useful component! :+1: I just wondered why `react-dom` was installed with this component.

To avoid bundlers bundling multiple versions of React or react-dom (the one that react-monaco-editor depends on and the one the own project depends on), both shouldn't be actual `dependencies` but rather `peerDependencies` and `devDependencies`.

**Comment by SamLebarbare** [comment]
+1 see my pull request

**Comment by superRaytin** [comment]
Done, thanks!
