### ISSUE TITLE
how to change font size of editor line number and code 

### ISSUE THREAD

**Issue by zhaoturing** [superRaytin/react-monaco-editor#152]

**Comment by sdc224** [comment]
@zhaoturing can you please add here some comments on how to do it?

From the docs, what I can get is if you add

```js
<Editor
        options={{ fontSize: 14 }}
/>
```

it should work.

I tried using the above code, but still it is not getting this exact font size (14px).

What I feel is, if you have any global CSS where you are overriding span, it will never work.

I also tried changing the local css using `styled-components`, though font size changes, selection inside editor breaks.
