### ISSUE TITLE
Not able to change`options`, once its rendered

### ISSUE THREAD

**Issue by ishantmehtaharness** [superRaytin/react-monaco-editor#156]
Once I pass initial `options` to React Monaco Editor, and on next render, I update options and pass again, 
eg, in my case, readOnly is initially false, then its true on next render. But React Monaco Editor is not changing its readOnly state.

**Comment by boenfu** [comment]
I also met.

**Comment by domoritz** [comment]
Can you send a PR to fix this behavior?
