### ISSUE TITLE
There is no document formatter for 'sql'-files installed.

### ISSUE THREAD

**Issue by iamyadi** [superRaytin/react-monaco-editor#159]
when I use react-monaco-editor, I want to click a button and then format the value. 
The click function code is this:
  handleFormat = ()=>{
    const { editor } = this.state
    setTimeout(function() {
      editor.getAction('editor.action.formatDocument').run();
    }, 300);
  }

and here I set editor to state:
  editorDidMount (editor, monaco) {
    this.setState({
      monaco,
      editor
    })
    editor.focus()
  }

The result is I got ''There is no document formatter for 'sql'-files installed.'', 
So I want to ask how can I add formatter document for 'sql'  and Implement this format function?

Thank you very much!

**Comment by domoritz** [comment]
This is a monaco question, not an issue with this repo.
