### ISSUE TITLE
Upgrade to monaco 0.8.0

### ISSUE THREAD

**Issue by mhr3** [superRaytin/react-monaco-editor#16]
The title says it all :)

**Comment by mhr3** [comment]
Unfortunately you forgot to bump the dep - https://github.com/superRaytin/react-monaco-editor/commit/f274451d7d8380ff40bf4e76121f576b8764f898#commitcomment-21101799

**Comment by superRaytin** [comment]
Fixed, sorry for this stupid mistake!
