### ISSUE TITLE
switching between files in editor

### ISSUE THREAD

**Issue by veeramarni** [superRaytin/react-monaco-editor#160]
Is there a way we can switch files in the editor.  When we need to open file in an already opened editor and when we switch files, right now we are only updating the `values` in the monaco-editor, which really not right has the editor's model will have old `versionId`, `EOL` etc. 

How can we update the model to the previous versionId when we switch files in the editor?

**Comment by domoritz** [comment]
This is a monaco question and is not specific to this library. Please ask it in the appropriate place.
