### ISSUE TITLE
Upgrade to 0.21.0 broke syntax highlighting

### ISSUE THREAD

**Issue by bcbrian** [superRaytin/react-monaco-editor#161]
Just pulled down newest version and Syntax highlighting is broken.

I created a codesanbox.io to show it happing but for some reason I cannot get the older version work :(
https://codesandbox.io/s/5qw3wxm3k <= missing syntax highlighting.

But if you set up the same thing locally it gets fixed by reverting. There is a download button in the codesandbox.

If I get time I will try to debug further.

**Comment by domoritz** [comment]
The example at https://github.com/superRaytin/react-monaco-editor/tree/master/example works fine. I think the issue is that you have to use the monaco webpack plugin at https://github.com/superRaytin/react-monaco-editor/blob/fab51f96a7e8e0172dea5f2f44ebc3cc3209c294/example/webpack.config.js#L36.

**Comment by bcbrian** [comment]
So now it is a requirement to use the webpack plugin... breaking change?

**Comment by bcbrian** [comment]
Ejected my CRA :( it works even better than before...

**Comment by domoritz** [comment]
I didn't know it worked before, tbh. I don't think it's a requirement to use that plugin but you need to add the right files and webpack by default doesn't do that.

**Comment by mats68** [comment]
I see also context menu doesn't work.
@domoritz how can I make 0.21.0 work when I use CRA if I don't want to eject ? 
(v. 0.20.0 works though I have to change language to 'java')

**Comment by domoritz** [comment]
Check the Monaco instructions. They explain how to add the necessary files.

**Comment by forgo** [comment]
@domoritz Can you elaborate or give a link on the "Monaco instructions"?

I am new to Monaco Editor entirely, and I am using `FuseBox` as my bundler and not `Webpack`, so I do not have the luxury of using `MonacoWebpackPlugin`.  My editor is loading fine in React, but there is no syntax highlighting.

**Comment by domoritz** [comment]
I was talking about the instructions at https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-esm.md. Unfortunately, it's quite complicated which is why I suggest the monaco webpack plugin.
