### ISSUE TITLE
Fix TypeScript types

### ISSUE THREAD

**Issue by nikeee** [superRaytin/react-monaco-editor#164]
The TS definitions were not updates in b1c212b9769f4ddb89b878daa68be26d6a9e9252. The change should also be reflected in the [index.d.ts](https://github.com/superRaytin/react-monaco-editor/blob/master/src/index.d.ts).

**Comment by domoritz** [comment]
Can you be more specific what's wrong and send a PR? Thanks!

**Comment by nikeee** [comment]
The `editorWillMount` method was changed to return the options. The type of this function does not state that:
https://github.com/superRaytin/react-monaco-editor/blob/master/src/index.d.ts#L14 (instead, it just returns `void`, because it has not been changed aswell).

I can send a PR, but not now.

**Comment by domoritz** [comment]
Thank you!
