### ISSUE TITLE
Enable/document usage without Webpack plugin

### ISSUE THREAD

**Issue by TimoSta** [superRaytin/react-monaco-editor#165]
According to the documentation, the Webpack plugin is required for monaco to function correctly, and it looks like without it, syntax highlighting etc. do not work correctly.

Now, we're using a build toolchain that is shared between multiple applications, and amending our webpack config is not trivial for this reason. I'm assuming that the same issue should pop up for users of create-react-app, as the webpack config isn't changeable in this case either?

From what I can tell, the plugin bakes language configs etc. into the application, which is then picked up by monaco. Am I right to assume that this can also be done from the application source itself?

Is there documentation available that describes how this can be achieved? If not, is there any interest in adding this to the docs?

**Comment by domoritz** [comment]
Can you send a PR?

**Comment by TimoSta** [comment]
We decided to go the Webpack plugin route after all, since the added complexity of doing it by hand didn't  seem reasonable after some preliminary research.

With this in mind, I won't be able to document the exact steps necessary unfortunately.

From my perspective, this issue can be closed, or we can keep it open in case someone else wants to take it on.
