### ISSUE TITLE
No autocomplete suggestions for document, window

### ISSUE THREAD

**Issue by DylanSp** [superRaytin/react-monaco-editor#166]
When creating a simple `<MonacoEditor>` element, it displays in the browser, I get autocomplete suggestions for variables I write in the editor, but I don't see autocomplete/Intellisense for `document` or `window`. In the [Monaco playground](https://microsoft.github.io/monaco-editor/playground.html#creating-the-editor-hello-world), these display without any configuration required. Do I need to set some configuration options/props, or is this a bug?

I'm using version 0.20.0 so I can use this with create-react-app without ejecting and using the Webpack plugin; let me know if that might be causing this issue.

**Comment by domoritz** [comment]
Try to eject and use the Monaco webpack plugin.

**Comment by DonsWayo** [comment]
For people with this issue, remember to add the languages in the Monaco webpack plugin
` new MonacoWebpackPlugin({
      // available options are documented at https://github.com/Microsoft/monaco-editor-webpack-plugin#options
      languages: ['json',  'javascript', 'typescript']
    })`
