### ISSUE TITLE
Json schema validation no error highlighting

### ISSUE THREAD

**Issue by ftcvlad** [superRaytin/react-monaco-editor#167]
I'm trying to run the provided example, where AnotherEditor component defines the following schema:
```
 {
          type: 'object',
          properties: {
            p1: {
              enum: [ 'v1', 'v2']
            },
            p2: {
              $ref: 'http://myserver/bar-schema.json'
            }
          }
 }
```

when I type in **"p1":**  I get a hint suggesting possible values ("v1", "v2"). When I further type **"p1":"hello"** , the erroneous value is not highlighted. 

This does work at Microsoft Monaco Editor's playground.

I'm using the latest version of react-monaco-editor.

Could you confirm that schema validation is working properly?

**Comment by ftcvlad** [comment]
I'm trying to run the provided example exactly as is, so, yes

**Comment by domoritz** [comment]
Hmm, interesting. Autocomplete works for me. 

<img width="610" alt="screen shot 2018-11-21 at 09 56 02" src="https://user-images.githubusercontent.com/589034/48859723-bba56200-ed73-11e8-8a15-f9423a1fdedd.png">

**Comment by ftcvlad** [comment]
it seems need to set validate:true. setDiagnosticsOptions overwrites default true value if not provided

also in the example i think no need to use requireConfig, since you use plugin

**Comment by domoritz** [comment]
Can you send a PR to fix the example? Thanks for flagging this!

**Comment by domoritz** [comment]
No problem. This was bugging me so I just went ahead. You can send a PR to update the readme.
