### ISSUE TITLE
Editor not showing with Bootstrap tab panes

### ISSUE THREAD

**Issue by Ahsan2** [superRaytin/react-monaco-editor#169]
The editor works fine, but when I use it with bootstrap tab panes (https://getbootstrap.com/docs/4.0/components/navs/#tabs) and toggle to the pane where the editor is residing then nothing shows up. It works fine when the first tab panel is the one where editor exists. Note that I am not using any reactstrap or react-bootstrap

**Comment by domoritz** [comment]
This sounds like an issue with bootstrap and we unfortunately don't provide support for other libraries.

**Comment by Ahsan2** [comment]
Actually bootstrap just sets the "display" css property of the html element to "none". So you are right, this is not an issue but more of a query, which is how to display the editor when it was initially set to "none" when the html first loads. Setting it to "block" afterwards is what makes the editor not show up

**Comment by clarencejychan** [comment]
@ahsan-sabir did you ever figure this out?

**Comment by ischenkodv** [comment]
@clarencejychan I had the same problem and fixed it by updating the layout after tab shown. It is done by `editor.layout()` function:

```
editorDidMount(editor) {
  this.editor = editor;
}

render() {
  const onSelect = (tab) => {
    if (tab == 'two') {
        this.editor.layout({width: 800, height: 600});
    }
  };

  return <Tabs onSelect={onSelect}>
    <Tab eventKey="one">... first tab ...</Tab>
    <Tab eventKey="two">
      <MonacoEditor
        width="800"
        height="600"
        language="javascript"
        theme="vs-dark"
        value={code}
        options={options}
        onChange={this.onChange}
        editorDidMount={this.editorDidMount}
      />
    </Tab>
  </Tabs>
}
```
