### ISSUE TITLE
You are manually calling a React.PropTypes validation function for the `width` prop on `MonacoEditor`.

### ISSUE THREAD

**Issue by ozluy** [superRaytin/react-monaco-editor#17]
I got following errors on console and component could not render.

![screen shot 2017-02-06 at 15 47 00](https://cloud.githubusercontent.com/assets/2522722/22647566/f94b2230-ec7a-11e6-9e6e-a4e660aa7b42.png)

**Comment by superRaytin** [comment]
It works well in my local environment, please tell me how can i reproduce this?
