### ISSUE TITLE
Autosuggest not showing

### ISSUE THREAD

**Issue by suryaVemp** [superRaytin/react-monaco-editor#173]
Hi,
I have followed the installation setup to bring in the monaco editor into my application. The syntax highlighter seems to work for the language specified in the Monaco component, but Im not getting any auto suggest results. When i hit the ctrl+ space I get "loading" in my auto suggest results.  Is there anything further i should do for the setup.

**Comment by suryaVemp** [comment]
I was trying the example, there are two editors in it. Im having an error with second one in line 80     (monaco.languages.json.jsonDefaults.setDiagnosticsOptions({) Cannot read property 'jsonDefaults' of undefined . So I removed that component and tested the first one and im having the issue here as well. The syntax highlighters seem to work but I was hoping to see javascript specific auto suggests like how vscode works.

**Comment by domoritz** [comment]
The example works fine for me. Make sure to install the dependencies with yarn. I think there is something different in your setup.

**Comment by suryaVemp** [comment]
Thank you it is working for me, I was using npm earlier, switching over to yarn did the trick.

**Comment by domoritz** [comment]
Great!

**Comment by Thara-pearlly** [comment]
> Thank you it is working for me, I was using npm earlier, switching over to yarn did the trick.

Im facing the same issue, 
was it just converting npm to yarn, or you added / modified any other
