### ISSUE TITLE
Testing with Jest fails to import monaco

### ISSUE THREAD

**Issue by adngdb** [superRaytin/react-monaco-editor#176]
Hi, 

First of all, I'm sorry if this is not the right place. I'm at a loss, and there are many parts involved in my question.

I am trying to run my test suite while using the Monaco editor. I use `create-react-app`, thus React and jest, and when I run tests, I get the following error:

```
/home/js/jest-react-monaco/node_modules/monaco-editor/esm/vs/editor/editor.api.js:5
import { PolyfillPromise } from '../base/common/winjs.polyfill.promise.js';
           ^

SyntaxError: Unexpected token {
 at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
```

However, when browsing to my website, the editor loads correctly. 

Steps to reproduce: 

```
create-react-app jest-monaco-test 
cd jest-monaco-test/
yarn add monaco-editor monaco-editor-webpack-plugin react-monaco-editor
```

Edit App.js and add:

```js
import MonacoEditor from 'react-monaco-editor';
```

Then run tests with `yarn test ` and get the above error.

I have no idea if this is a problem with `jest`, `create-react-app`, `monaco-editor` or `react-monaco-error`, or that I simply missed something. Any help will be appreciated. :-)

**Comment by adngdb** [comment]
A colleague of mine made the hypothesis that this line is the culprit: https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L1

```js
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
```

This forces an import of an ES module, which jest doesn't support yet. What confused me was that I didn't know that jest was using transpiled code. Anyway, solutions here would be to A. import `monaco` differently so that it can use transpiled code where necessary or B. wait for [Jest to support ES modules](https://github.com/facebook/jest/issues/4842) (but that might take some time).

**Comment by domoritz** [comment]
Hmm, the issues with esm keep coming up but it allows much smaller bundles. Could you transpire with Babel in jest to make things work?

**Comment by x5engine** [comment]
so what's the solution?

**Comment by adngdb** [comment]
My solution was to use a different code editor for now, and reinvestigate using Monaco once Jest supports ESM. I'm sure there are other ways around this problem but I don't know them and don't plan on finding them out. :-) 

I thus guess the solution to this is: wait for Jest. Hence, closing this. Thanks everyone!

**Comment by domoritz** [comment]
Sorry to hear that. Monaco is awesome but can be a bit tricky to set up. I hope things improve in the future.

**Comment by veeramarni** [comment]
Try this

jest.config.js
```
const { defaults } = require("jest-config");

module.exports = {
    testEnvironment: "jsdom",
    preset: "ts-jest",
    testMatch: null,
    testRegex: ".*test*\\.(ts|tsx|js)$",
    testPathIgnorePatterns: [
        "/node_modules/",
        "/dist/"
    ],
    transform: {
        "\\.(ts|tsx)$": "ts-jest",
        // Use our custom transformer only for the *.js and *.jsx files
         "\\.(js|jsx)?$": "./transform.js",
         // future need to test with 
        //  "^.+\\.(js|jsx|ts|tsx)$": "./transform.js",
        ".+\\.(css|styl|less|sass|scss)$": "jest-css-modules-transform"
    },
    moduleFileExtensions: [...defaults.moduleFileExtensions,
        "ts",
        "tsx",
        "js", "jsx"],
    moduleNameMapper: {
        '^__mocks__/(.*)$': '<rootDir>/../../__mocks__/$1',
        // This regex should match the packages that we want compiled from source
        // through `ts-jest`, as opposed to loaded from their output files in
        // `dist`.
        // We don't want to match `apollo-server-env` and
        // `apollo-engine-reporting-protobuf`, because these don't depend on
        // compilation but need to be initialized from as parto of `prepare`.
    },
    transformIgnorePatterns: [
        "/node_modules/(?!(@vscode)/).*/"
      ],
    clearMocks: true,
    }
};
```
transform.js
```
const config = {
  babelrc: false,
  presets: ["@babel/preset-env", "@babel/preset-react",
  // ["@babel/preset-typescript", { isTSX: true, allExtensions: true }]
],
  plugins: [
    ["@babel/plugin-proposal-class-properties", { loose: true }],
    "@babel/plugin-transform-runtime",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread",
  ],
};
module.exports = require("babel-jest").createTransformer(config);
```

**Comment by epicfaace** [comment]
Here's the solution that worked for me: https://github.com/react-monaco-editor/react-monaco-editor/issues/133#issuecomment-403960502

**Comment by lucataglia** [comment]
I have the same issue with Jest and Monaco and to make the tests pass I had to:

1. Add a moduleNameMapper for monaco-editor as @epicfaace suggest: [#133 (comment)](https://github.com/react-monaco-editor/react-monaco-editor/issues/133#issuecomment-403960502)
2. Configure a setupTests.js like explained here: [stackOverflow](https://stackoverflow.com/questions/42535270/regeneratorruntime-is-not-defined-when-running-jest-test/57439821#57439821)

I'm using: 
- "jest": "^24.9.0" 
-  "babel-jest": "24.9",
- "monaco-editor": "^0.20.0"
- "react-monaco-editor": "0.33.0",
- "monaco-editor-webpack-plugin": "^1.8.2",

**Comment by manstis** [comment]
For the purposes of prosperity and to help others I overcame my `react-monaco-editor`/`jest` issues by mocking `monaco-editor`

`jest.config.js`
```
module.exports = {
  moduleNameMapper: {
    "monaco-editor": "<rootDir>/__mocks__/monacoMock.js"
  }
};
```
I then added enough to `monacoMock.js` to fit my purposes (but others will have other needs).
```
module.exports = {
  languages: {
    register: function(language) {},
    setMonarchTokensProvider: function(name, tokens) {},
    registerCompletionItemProvider: function(name, provider) {}
  },
  editor: {
    defineTheme: function(name, theme) {}
  }
};
```

**Comment by tapjay** [comment]
@manstis prosperity to you, your approach with some changes fixed the issue for me

**Comment by CherpakovPhilipp** [comment]
I had also being struggled with this issue for couple of hours. 
I fixed it using following steps:

1. Create __mocks__ directory in the projects root (at the same level with node-modules);
2. Create 'monaco-editor.ts' that exports modules you need: 
`module.exports = {
  editor: {
    getModelMarkers: jest.fn().mockReturnValue([]),
    // ...other methods here
  },
  Position: {}
  // ...other modules here
};`

And that's it! When Jest parser finds imported 'monaco-editor' modules it looks in __mocks__ folder first where finds our created 'monaco-editor.ts' module. Then it takes all the required modules from here.

**Comment by vishalsatam** [comment]
I'm using @monaco-editor/react package and I followed the suggestion from this [comment](https://github.com/react-monaco-editor/react-monaco-editor/issues/133#issuecomment-403960502) by @sanusart 

This works for me:
```
    "transformIgnorePatterns": [
      "/node_modules/(?!(monaco-editor)).+\\.js$"
    ],
    "moduleNameMapper": {
      "^monaco-editor$": "<rootDir>/node_modules/@monaco-editor/react"
    }
```

**Comment by DiegoLibonati** [comment]
> "transformIgnorePatterns": [
>       "/node_modules/(?!(monaco-editor)).+\\.js$"
>     ],
>     "moduleNameMapper": {
>       "^monaco-editor$": "<rootDir>/node_modules/@monaco-editor/react"
>     }

This solution works in my project. THX!!!!!!
