### ISSUE TITLE
Build with react-scripts

### ISSUE THREAD

**Issue by bearzx** [superRaytin/react-monaco-editor#179]
Do you have and idea of how I can involve react-monaco in with the react-scripts file structures without changing the webpack configs? I tried by directly npm install it but didn't seem to work.

**Comment by manobi** [comment]
Same issue here. Create react app do no allow us to change webpack config file without ejecting, any to solve this?

**Comment by domoritz** [comment]
You can try to follow the instructions at https://github.com/Microsoft/monaco-editor-samples/blob/master/README.md. this is a general issue with Monaco and I don't think there is much we can do in this plugin. I'm going to close this issue but please report anything you might find out about how to use this extension with create react app.

**Comment by danvoyce** [comment]
Anyone make any progress on this? I really don't want to eject my create-react-app :/

**Comment by zicjin** [comment]
You can do a lot of things, like this: [suren-atoyan/monaco-react](https://github.com/suren-atoyan/monaco-react)

> You can try to follow the instructions at [Microsoft/monaco-editor-samples:README.md@`master`](https://github.com/Microsoft/monaco-editor-samples/blob/master/README.md) [](/Microsoft/monaco-editor-samples/blob/HEAD@{2019-01-27T18:05:55Z}/README.md). this is a general issue with Monaco and I don't think there is much we can do in this plugin. I'm going to close this issue but please report anything you might find out about how to use this extension with create react app.

**Comment by suren-atoyan** [comment]
Hello everyone, `there is always a way` 🙂 

In addition to [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react) I also published [@monaco-editor/loader](https://github.com/suren-atoyan/monaco-loader). So, if you need Monaco without webpack configuration, or even directly from CDN, check those libraries.

I hope it will help someone 🙂

**Comment by passos** [comment]
> Hello everyone, `there is always a way` 🙂
> 
> In addition to [@monaco-editor/react](https://github.com/suren-atoyan/monaco-react) I also published [@monaco-editor/loader](https://github.com/suren-atoyan/monaco-loader). So, if you need Monaco without webpack configuration, or even directly from CDN, check those libraries.
> 
> I hope it will help someone 🙂

this is an great project that is actually solving problem in a elegant way. now the `react-scripts` and `theme` are not a problem at all.
