### ISSUE TITLE
Context menu not work

### ISSUE THREAD

**Issue by lyudad** [superRaytin/react-monaco-editor#187]
Hello. I have run you example. And right click on editor not work. It open browser context menu instead of monaco-editor context menu  (according to your code you have not turned off context menu )

**Comment by lyudad** [comment]
I have noticed this issue happens if use npm

**Comment by domoritz** [comment]
Which browser are you using?

**Comment by lyudad** [comment]
Any, I have checked in chrome and opera

**Comment by lyudad** [comment]
New monaco-editor version  work fine
