### ISSUE TITLE
Mismatch in optional and mandatory props in documentation

### ISSUE THREAD

**Issue by SSoelvsten** [superRaytin/react-monaco-editor#188]
Trying to create a ReasonML wrapper I ran into the following confusion in the documentation for this component. From the examples in `README.md` and `index.d.ts` all props for the component seems optional, but the _Properties_ section in `README.md` only writes that `context` is optional.

Either _Properties_ does not reflect all being optional or the examples don't reflect all others being mandatory?

**Comment by domoritz** [comment]
Yeah, that doesn't seem right. Could you send a PR to resolve this?
