### ISSUE TITLE
Compiling Editor with webpack outputs more than 50 bundle files

### ISSUE THREAD

**Issue by RyanZhu1024** [superRaytin/react-monaco-editor#189]
After setting up the react monaco editor and testing it successfully, I realized there are lots of bundle files. Every time it compiles, it generates these. Any idea why this could happen? `reactapp.js` is our final bundle file. If the react monaco editor is not used, everything is fine.
<img width="403" alt="Screen Shot 2019-03-13 at 15 07 32" src="https://user-images.githubusercontent.com/2485275/54318023-3227d300-45a2-11e9-8df7-29d2146794b0.png">

**Comment by domoritz** [comment]
I don't know why this would happen but it seems like a webpack issue so I'll close this issue here.
