### ISSUE TITLE
Cursor loses position in controlled mode when componentDidUpdate

### ISSUE THREAD

**Issue by tarr11** [superRaytin/react-monaco-editor#19]
Repro:

Move the cursor in controlled mode
Update the page by calling setState  (eg., outside the editor)
Expect: Cursor to retain position
Instead: Cursor gets reset to start of editor

**Comment by tarr11** [comment]
Never mind, this was related to my application code.

**Comment by Lenois** [comment]
I think I am hitting the same issue, what ended up being your fix?

**Comment by slinkardbrandon** [comment]
I just ran into this too, I'm also curious about a fix

**Comment by Samdaaman** [comment]
I think it would be possible with having two states for the value or using the defaultValue prop.

However when I ran into the same problem, I found this package https://www.npmjs.com/package/@monaco-editor/react which seems to work much better

**Comment by Wildanzr** [comment]
I'm curious how to fix this.
