### ISSUE TITLE
 Uncaught AssertionError: path must be a string

### ISSUE THREAD

**Issue by dandingol03** [superRaytin/react-monaco-editor#21]
when i run this plugin in chrome,it just works fine,but...
recently,i need to finish a prototype tool with electron,however...
electron  throw the error which i have mentioned...
please,give me some help

**Comment by dvdhsu** [comment]
+1; same issue here; did you ever find a solution @dandingol03

**Comment by dvdhsu** [comment]
Have fixed it @dandingol03:

```function createWindow () {
  mainWindow = new BrowserWindow({
    webPreferences: { nodeIntegration: false },
    width: 800,
    height: 600,
  })
  ...
}
```

**Comment by uppe-r** [comment]
I don't think this is a solution @dvdhsu, it's more of a workaround, I'm looking for something better, but nothing yet.

**Comment by dandingol03** [comment]
@dvdhsu ,thanks a lot.but how can i use require in my render process.for example:

**Comment by uppe-r** [comment]
@dandingol03 [https://electron.atom.io/docs/faq/#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron](url)

**Comment by hengkx** [comment]
@dandingol03 Can you talk about how to solve this problem? Thanks

**Comment by uppe-r** [comment]
@hengkx @dvdhsu Got it working based on [https://github.com/reactide/reactide/blob/master/renderer/components/TextEditor.jsx](url). I ended up removing a lot of code just to try it out, neither did I use webpack copy plugin as described on README, but anyways, let me know if this worked fine.

```javascript
afterViewInit() {
    const amdRequire = global.require('monaco-editor/min/vs/loader.js').require;
    amdRequire.config({
      baseUrl: 'node_modules/monaco-editor/min/'
    });

    // workaround monaco-css not understanding the environment
    self.module = undefined;
    // workaround monaco-typescript not understanding the environment
    self.process.browser = true;
    amdRequire(['vs/editor/editor.main'], () => {
      this.initMonaco();
    });
  }
```

**Comment by dandingol03** [comment]
when i look through reacted,i found that the <b>web.pack.config.js</b> of the ide sets `target:electron`,and i did it too.
although i have made component `TextEditor` <b>compile through </b>,electron throws a new error:
![13e7ba9e-1e7d-460f-b1f3-268532053813](https://cloud.githubusercontent.com/assets/13013579/25777383/50d66314-330e-11e7-865a-13c433f3a89d.png)
@uppe-r  do you have any idea,thanks

**Comment by dandingol03** [comment]
after i set 'target: 'electron-renderer' in web pack.config.js,the problem i mentioned above has been dismissed.but i got a problem:<b>Could not find node_modules/monaco-editor/min/vs/editor/editor.main.css or it was empty</b>
here is my editor code:
```js
export default class TextEditor extends React.Component {
    constructor(props) {
        super();
    }

    componentDidMount() {
        let amdRequire = global.require('monaco-editor/min/vs/loader.js').require;
        var path = require('path');
        var fs = require('fs');
        //var file = fs.readFileSync(this.props.tab.path, { encoding: 'utf8' });
        function uriFromPath(_path) {
            var pathName = path.resolve(_path).replace(/\\/g, '/');
            if (pathName.length > 0 && pathName.charAt(0) !== '/') {
                pathName = '/' + pathName;
            }
            return encodeURI('file://' + pathName);
        }
        //
        // amdRequire.config({
        //     baseUrl: uriFromPath(path.resolve(__dirname, '../../../../node_modules/monaco-editor/min'))
        // });


        amdRequire.config({
            baseUrl: 'node_modules/monaco-editor/min/'
        });
        // workaround monaco-css not understanding the environment
        self.module = undefined;
        // workaround monaco-typescript not understanding the environment
        self.process.browser = true;
        const containerElement = this.refs.container;
        var editor;
        amdRequire(['vs/editor/editor.main'], () => {
            editor = monaco.editor.create(containerElement, {
                value: 'hello monaco',
                language: 'javascript',
                theme: "vs-dark",
            });
            //this.props.addEditorInstance(editor, id);

            // window.addEventListener('resize', () => {
            //     if (id === this.props.activeTab) {
            //         let editorNode = document.getElementById(id);
            //         let parent = editorNode.parentElement;
            //         editorNode.style.width = parent.clientWidth;
            //         editorNode.firstElementChild.style.width = parent.clientWidth;
            //         editorNode.firstElementChild.firstElementChild.style.width = parent.clientWidth;
            //         editorNode.getElementsByClassName('monaco-scrollable-element')[0].style.width = parent.clientWidth - 46;
            //     }
            // })
        });
    }

    render() {
        return (
                <div className="editor-container" ref="container"
                    style={{ height: '100%', width: '100%' }}
                ></div>
        );
    }
}
```
give me some help,thanks for your time @uppe-r

**Comment by dandingol03** [comment]
i solved the problem by putting a link to the css in index.html.
but when i am typing in the editor component,got another problem 
![50cb3131-2d03-4345-8dfa-e8ddf9f4379d](https://cloud.githubusercontent.com/assets/13013579/25777702/cbfe58f4-3317-11e7-8e0f-50f46f266454.png)

**Comment by dandingol03** [comment]
problem solved!!!
here is my code
`index.html`:
```js
<script>
    // Monaco uses a custom amd loader that over-rides node's require.
    // Keep a reference to node's require so we can restore it after executing the amd loader file.
    var nodeRequire = global.require;
</script>
<script src="../node_modules/monaco-editor/min/vs/loader.js"></script>
<script>
    // Save Monaco's amd require and restore Node's require
    var amdRequire = global.require;
    global.require = nodeRequire;
    var path = require('path');
    function uriFromPath(_path) {
        var pathName = path.resolve(_path).replace(/\\/g, '/');
        if (pathName.length > 0 && pathName.charAt(0) !== '/') {
            pathName = '/' + pathName;
        }
        return encodeURI('file://' + pathName);
    }
    amdRequire.config({
        baseUrl: uriFromPath(path.join(__dirname, '../node_modules/monaco-editor/min'))
    });
    self.module = undefined;
    // workaround monaco-typescript not understanding the environment
    self.process.browser = true;
</script>
```
`TextEditor.jsx`
```js
 const containerElement = this.refs.container;
        var editor;
        amdRequire(['vs/editor/editor.main'], () => {
            editor = monaco.editor.create(containerElement, {
                value: 'hello monaco',
                language: 'javascript',
                theme: "vs-dark",
            });
});
```
`webpack.config.js`
```js
  target: 'electron-renderer',
```
thanks to everyone in this activity,i become more interested and devoted in monaco.
problem shut down  @dvdhsu  @uppe-r  @hengkx

**Comment by michaelerobertsjr** [comment]
@dandingol03 This example would be much better if it were a complete code example.  I had to use one of the other work arounds and just use monaco-editor directly.

Would you you mind posting a link to a gist or repo with a working example?

**Comment by nitishvini** [comment]
const express=require('express');
const bodyparser=require("body-parser");
const request=require('request');
const app=express();
app.use(express.static("public"));
app.use(bodyparser.urlencoded({extended:true}));
app.get("/",function(req,res){res.sendFile(__dirname+"/signup.html")});
app.post("/",function(req,res){
  var options={
    url:"https://us20.api.mailchimp.com/3.0/lists/65193e1caf",
    method:"POST",
    headers:{
      "authorization":"nithish ccd3568b789292a3e3a925833c2e2fa5-us20",}
    };
  require(["options"],function (error,res,body){
    if(error)
    console.log(error);
    else {
      console.log(body.statusCode);
    }
  });
});
app.listen(3000,function(){console.log("runs on 3000")});

**Comment by nitishvini** [comment]
i am getting error of (AssertionError: path must be a string) can u help
