### ISSUE TITLE
Default height is not working

### ISSUE THREAD

**Issue by Yeti-or** [superRaytin/react-monaco-editor#22]
in ReadMe default height is `500` but in code it's `100%`.
And so without height of wrap is really `100%` but monaco-editor's height become `5px`

**Comment by kevinkid** [comment]
Nice work ! am working on something using the editor and for now am just rendering the editor inside a div container and listening for resize events for triggering a rerender of the editor . Am working on it .

**Comment by domoritz** [comment]
@kevinkid Can you share how you did it?
