### ISSUE TITLE
`vs/loader.js` path not correct with react-router

### ISSUE THREAD

**Issue by dragfire** [superRaytin/react-monaco-editor#25]
I'm using `react-router` and `CopyWebpackPlugin`, it's working for normal paths like

`<Route path="/editor" component={Editor} /> // this one is working fine`

The problem is with this one with an path variable `editorId`, it can be any random id:    

`<Route path="/editor/:editorId" component={Editor} /> 
`    

It only tries to load from `http://localhost:3000/editor` which throws a `404` in this case.
    
Can you help me out? Thanks.

**Comment by kevinkidin** [comment]
Failed to create challenge
Status code: undefined
Response body:
```
"empty response"
```

**Comment by kevinkidin** [comment]
Failed to create challenge
Status code: 503
Response body:
```
"<!DOCTYPE html>\n\t<html>\n\t  <head>\n\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>Application Error</title>\n\t\t<style media=\"screen\">\n\t\t  html,body,iframe {\n\t\t\tmargin: 0;\n\t\t\tpadding: 0;\n\t\t  }\n\t\t  html,body {\n\t\t\theight: 100%;\n\t\t\toverflow: hidden;\n\t\t  }\n\t\t  iframe {\n\t\t\twidth: 100%;\n\t\t\theight: 100%;\n\t\t\tborder: 0;\n\t\t  }\n\t\t</style>\n\t  </head>\n\t  <body>\n\t\t<iframe src=\"//www.herokucdn.com/error-pages/application-error.html\"></iframe>\n\t  </body>\n\t</html>"
```

**Comment by joewood** [comment]
I had the same issue. The fix was to configure the vs-loader to use a URL prefix for the files that it is loading.  So, I load the AMD loader as before, but with an absolute path:
```javascript
if (typeof window["require"] === "undefined") {
	var loaderScript = window.document.createElement("script");
	loaderScript.type = "text/javascript";
	loaderScript.src = "/vs/loader.js";  // <---- absolute path
	loaderScript.addEventListener("load", aferLoad);
	window.document.body.appendChild(loaderScript);
} else {
        afterLoad();
}
```

The key is to configure the AMD loader after it has been loaded. The `afterLoad` callback function is invoked after loading (or just invoked immediately if the loader has been loaded). In this callback I do this:
```javascript
const afterLoad = () => {
	window["require"]["config"]({ baseUrl: "/" });  // <-- configuration to use absolute paths for everything
	window["require"](["vs/editor/editor.main"], () => {
            // do other stuff
	});
};
```

**Comment by dragfire** [comment]
I solved it using: 

```
  const requireConfig = {
      url: 'https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.1/require.min.js',
      paths: {
        vs: 'http://localhost:3000/vs',
      },
    };
```

**Comment by lingxufeng2014** [comment]
`componentDidMount() {
        const afterLoad = () => {
            window.require.config({ baseUrl: '/' });  // <-- configuration to use absolute paths for everything
            window.require(['vs/editor/editor.main'], () => {
                MonacoEditor = require('react-monaco-editor').default;
                this.setState({
                    ...this.state,
                    monacoLoaded: true
                });
            });
        };
        if (typeof window.require === 'undefined') {
            const loaderScript = window.document.createElement('script');
            loaderScript.type = 'text/javascript';
            loaderScript.src = '/vs/loader.js';  // <---- absolute path
            loaderScript.addEventListener('load', afterLoad);
            window.document.body.appendChild(loaderScript);
        }
        else {
            afterLoad();
        }
    }`

**Comment by lingxufeng2014** [comment]
just after @joewood 's code

**Comment by expobrain** [comment]
Closing this issue, feel free to reopen it if necessary
