### ISSUE TITLE
Inconsistency with Electron

### ISSUE THREAD

**Issue by zxqfox** [superRaytin/react-monaco-editor#27]
Electron `env` has require, while Monaco uses require as ADM loaded marker.

Sample: https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-electron/index.html
Some more discussions: https://github.com/Microsoft/monaco-editor/issues/90

**Comment by peteboothroyd** [comment]
Has this been fixed yet? I have the workaround as detailed here in issue [21](https://github.com/superRaytin/react-monaco-editor/issues/21) working, but then I'm not using MonacoEditor!

**Comment by expobrain** [comment]
@peteboothroyd Absolutely yes! I can add an example of using `react-monaco-editor` with Electron in the `examples` folder which includes you changes
