### ISSUE TITLE
Support numeric width and height properties also

### ISSUE THREAD

**Issue by bvaughn** [superRaytin/react-monaco-editor#3]
First off, thanks for creating this wrapper component! 😄

I think it would be nice to change the `width` and `height` prop types though, since width/height is usually numeric within the context of React components. You could support real-number and percentage based dimensions using `PropTypes.oneOf` like so:

```cs
  width: PropTypes.oneOf([PropTypes.string, PropTypes.number]),
  height: PropTypes.oneOf([PropTypes.string, PropTypes.number]),
```

As it is currently, we have to convert numeric values to strings (which is no big deal of course, but could be nicer if handled by the component):

```jsx
<MonacoEditor
  height={`${height}px`}
  width={`${width}px`}
  {...props}
/>
```

If your component supported either numbers _or_ strings the above string creation (with `px` suffix) would be handled automatically by React. 😄

**Comment by superRaytin** [comment]
Sorry for my late reply. I have fixed this, thanks!

**Comment by bvaughn** [comment]
Thank you!
