### ISSUE TITLE
Component not responding to change in model correctly

### ISSUE THREAD

**Issue by joewood** [superRaytin/react-monaco-editor#31]
If I create a ReactMonacoEditor component with a key of `editor` and a model set-up in `options`, like this:
```typescript
<MonacoEditor
	key="editor"
	options={{ ...options, model: model }}
	language="typescript"
	editorWillMount={this.editorWillMount}
	editorDidMount={this.editorDidMount}
/>
```

When the model property changes in `options` the editor does not repopulate with the new file. The old model from the previous set of properties is still active. The workaround is to generate a new key for each model URI, but it would be nice to fix this in the component:
```typescript
<MonacoEditor
	key={"editor" + model.uri.toString()}
```

**Comment by expobrain** [comment]
Hi @joewood, can you provide a small example showing how you create and update the model?

**Comment by James9074** [comment]
To touch on this, I noticed changed `options` don't reflect in the editor either, at least not after it has mounted, even on re-renders.

**Comment by gunn** [comment]
It's clear why this is - the options are applied in `initMonaco` which runs at init and never again. Perhaps they should be reapplied in a `componentWillUpdate(newProps)` method.

**Comment by expobrain** [comment]
Closing this because fix has been merged on master. However if there are any other problems feel free to reopen this issue

**Comment by KutnerUri** [comment]
I don't see an applied? #48 is another issue.

Editor should call ```editorInstance.updateOptions()``` at ```componentDidUpdate(prevProps)```.
(Maybe optimize to call only on change in props.options...)

I will write the fix if I have the time
