### ISSUE TITLE
Error: Cannot resolve module 'file' in E:\GitHub\react-monaco-editor\examples

### ISSUE THREAD

**Issue by tracksaw** [superRaytin/react-monaco-editor#33]
Followed the instructions to the letter, but get the above error when I run "npm start".

Does anyone else see this problem?

BTW. I tried "npm install file --save" and "npm install file-loader". The error then became "ERROR in path must be a string".

**Comment by Phantomape** [comment]
I got the same error, LOL

**Comment by expobrain** [comment]
It's fixed in #30

**Comment by domoritz** [comment]
Fixed in master. Please reopen if you still have issues.
