### ISSUE TITLE
Upgrade MonacoEditor to 0.9.0

### ISSUE THREAD

**Issue by tarr11** [superRaytin/react-monaco-editor#34]
https://github.com/Microsoft/monaco-editor/releases/tag/v0.9.0

**Comment by domoritz** [comment]
Done.

**Comment by FelixHenninger** [comment]
Hi @domoritz and @expobrain, just chiming in to send a big thanks to you and everyone else who has worked on the updates over the past weeks! This is something I couldn't have done, but I'm super-glad that you have the expertise and took the time to maintain this hugely useful package. If I can get you a portion of your preferred beverage, do let me know ;-) . Cheers, a very grateful (end-) user
