### ISSUE TITLE
Accessing proptypes via the main React package is deprecated

### ISSUE THREAD

**Issue by tarr11** [superRaytin/react-monaco-editor#37]
`Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
`
https://github.com/superRaytin/react-monaco-editor/blob/master/src/index.js#L143-L159

**Comment by expobrain** [comment]
The pull request #24 is fixing this already

**Comment by domoritz** [comment]
Fixed in master.
