### ISSUE TITLE
context.monaco.editor.setTheme is not a function

### ISSUE THREAD

**Issue by mwkang** [superRaytin/react-monaco-editor#43]
Hello,

I use a react-monaco-editor in in-house service.
Thanks for developing this project.

Recently I updated react-monaco-editor's version.
My package.json

```
"monaco-editor": "~0.9.x",
"react-monaco-editor": "~0.9.x",
```

After that, I got a error `Uncaught TypeError: context.monaco.editor.setTheme is not a function`.
Can you take a look at it?

Best regards,
Minwoo Kang.

**Comment by domoritz** [comment]
Hmm, are you sure that monaco is in version 0.9? It sounds like you still have 0.8 installed.

**Comment by mwkang** [comment]
I will check. Thank you!

**Comment by DCarty** [comment]
Same issue: monaco.editor.setTheme is not a function version: 0.10.1
