### ISSUE TITLE
monaco-editor dependency

### ISSUE THREAD

**Issue by expobrain** [superRaytin/react-monaco-editor#45]
As version 0.9.0 `monaco-editor` is a peer dependency, that is if you install `react-monaco-editor` package you need to install the `monaco-editor` package as well.

Now, there are two options:

- update the readme stating that the command to install the package is `npm install react-monaco-editor monaco-editor`
- move back `monaco-editor` as a dependency

I feel that the second option make more sense to me, `react-monaco-editor` is a component which wraps the editor not a plugin of the editor, but that it's just my humble opinion.

@domoritz what you think about this?

**Comment by domoritz** [comment]
I agree. Let's bring monaco back. https://github.com/superRaytin/react-monaco-editor/pull/47

**Comment by domoritz** [comment]
I made a new release

**Comment by expobrain** [comment]
Cool, thanks!
