### ISSUE TITLE
Setting JSON schema for Monaco editor with language set to JSON

### ISSUE THREAD

**Issue by aaronpcz** [superRaytin/react-monaco-editor#5]
Hi,

Firstly I'd like to thank you for creating this react module for the Monaco editor.

I have a simple query:

How can I set some JSON language options for using the Monaco Editor using this module.  I wish to set a JSON schema following...

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

and

https://code.visualstudio.com/docs/languages/json

I've tried various routes but this.refs.monaco.editor.languages is undefined.

Any ideas?

Thanks,
Aaron

**Comment by superRaytin** [comment]
Hi @aaronpcz , upgrade to `0.6.x` and use `editorWillMount(monaco)` could help you.

demo: https://github.com/superRaytin/react-monaco-editor#do-something-before-editor-mounted

**Comment by aaronpcz** [comment]
Hi @superRaytin 

Much appreciated thank you.
