### ISSUE TITLE
Editor does not resize

### ISSUE THREAD

**Issue by peteboothroyd** [superRaytin/react-monaco-editor#53]
The monaco-editor component does not update to match the dimensions of the container it is within 
 when the container resizes. This only affects when a percentage height or width is supplied.
I believe this may be accomplished by calling editor.layout() but have not been able to make it work yet.

**Comment by ThomasBrekelmans** [comment]
You are on the right track with calling editor.layout().

You'll need a reference to the 'editor', which can be obtained by implementing the 'editorDidMount' prop on your <MonacoEditor /> instance.

Then you need to listen for resize events, and call (this.)editor.layout() in your event handler.

Here's a very basic ResizableMonacoEditor component which illustrates this:
`
class ResizableMonacoEditor extends Component {
	editor = null;

	handleEditorDidMount = editor => this.editor = editor;

	render() {
		return (
			<MonacoEditor
				{ ...this.props }
				editorDidMount={this.handleEditorDidMount}
			/>
		);
	}

	handleResize = () => this.editor.layout();

	componentDidMount() {
		window.addEventListener('resize', this.handleResize);
	}
}
`

Of course you are free to 'listen for resize events' in a more elegant way. For example by using one of the many community example React components for detecting resizes for individual elements/components.
But I think that's outside the scope of your question so I opted for a simpler / more straightforward example.

Note: by spreading { ...this.props } on <MonacoEditor /> you can set any prop on <ResizableMonacoEditor /> intended for <MonacoEditor />.

Hope this helps.

**Comment by domoritz** [comment]
You can also set monaco to autosize.

**Comment by ThomasBrekelmans** [comment]
Which might cause performance problems as outlined in this issue from the monaco project:
https://github.com/Microsoft/monaco-editor/issues/28

So if that might be a concern, I'd agree with the recommendation (in that issue) of handling resizes manually and use something like I suggested.

**Comment by expobrain** [comment]
So shall we close this issue?

**Comment by expobrain** [comment]
Closing this issue for now, please feel free to open it again if necessary

**Comment by milesmeow** [comment]
I'm using react-split-pane (using a left / right pane configuration) and am putting the react-monaco-editor in the secondary pane.

The resize code works for when I expand the window.  The editor expands to fill the secondary pane.  I can see the minimap and the vertical scrollbar on the right.

_However_, when I shrink down the window, the editor does not shrink. Basically the minimap and the scrollbars can't be seen anymore.  They are off the bounds of the window.

**Comment by DaxChen** [comment]
```js
import React from 'react';
import MonacoEditor from 'react-monaco-editor';
import ReactResizeDetector from 'react-resize-detector';

export default class Editor extends React.Component {
  state = {
    code: ['function x() {', "  console.log('Hello world!');", '}'].join('\n'),
  };

  onChange = (newValue, e) => {
    console.log('onChange', newValue, e);
    this.setState({ code: newValue });
  };

  editorDidMount = (editor, monaco) => {
    console.log('editorDidMount', editor, monaco);
    this.editor = editor;
    editor.focus();
  };

  render() {
    const { code } = this.state;
    const options = {
      selectOnLineNumbers: true,
    };
    return (
      <ReactResizeDetector
        handleWidth
        handleHeight
        onResize={() => {
          if (this.editor) {
            this.editor.layout();
          }
        }}
      >
        <MonacoEditor
          language="javascript"
          theme="vs-dark"
          value={code}
          options={options}
          onChange={this.onChange}
          editorDidMount={this.editorDidMount}
        />
      </ReactResizeDetector>
    );
  }
}
```

**Comment by miquelvir** [comment]
This is not working for me when calling .layout() without parameters. Calling .layout({}) happens to work. 

Source: https://stackoverflow.com/a/64485730/9415337
