### ISSUE TITLE
Solidity language 

### ISSUE THREAD

**Issue by Tanooj0902** [superRaytin/react-monaco-editor#60]
Hi, I am unable to get the solidity language in the new version. Also I tried to downgrade the version and reinstalled it but the solidity language support is not theres.

**Comment by expobrain** [comment]
I've just checked the (latest version)[https://microsoft.github.io/monaco-editor/] of Monaco and and the Solidity language has the `sol` identifier in the editor, setting it in the `react-monaco-editor` options works as well.

TBF I was using `solidity` as a language's identifier and it reverted back to `plaintext`, is this your case?

**Comment by domoritz** [comment]
@Tanooj0902 Please reopen if you're still having issues.

**Comment by j2kenton** [comment]
We also experienced this.
I would like to ask:
@domoritz closed this issue as `as designed` or perhaps we need to be consistent and use `solidity` and not `sol`, as in the [documentation](https://github.com/Microsoft/monaco-editor-webpack-plugin#options) 
Thanks!
