### ISSUE TITLE
example of calling defineTheme

### ISSUE THREAD

**Issue by piotrpMSFT** [superRaytin/react-monaco-editor#62]
Hi,
  I'm trying to define a custom theme in react-monaco-editor but am seeing a silent failure. I am trying to invoke defineTheme in editorWillMount:

```
    private editorWillMount = (monacoModule: typeof monaco) => {
        monaco.editor.defineTheme("myCustomTheme", {
            base: 'vs', // can also be vs-dark or hc-black
            inherit: true, // can also be false to completely replace the builtin rules
            rules: [
                { token: 'comment', foreground: 'ffa500', fontStyle: 'italic underline' },
                { token: 'comment.js', foreground: '008800', fontStyle: 'bold' },
                { token: 'comment.css', foreground: '0000ff' } // will inherit fontStyle from `comment` above
            ]
        });
    }
```
Do note that I'm using typescript, so syntax is slightly different.

I then initialize the editor with the same theme name, but the custom theme does not take. Has anyone had luck enabling this scenario, and if so... how?

**Comment by piotrpMSFT** [comment]
Ok, I got a bit closer. Looks like the theme is being defined correctly and I'm able to set it. however, it looks like by the time that editorWillMount is invoked it's too late to define a new theme that that editor should use. In other words, I believe that this is happening:

 - react-monaco-editor loads the monaco-editor scripts
 - react-monaco-editor invokes monaco.editor.create with my new theme
 - monaco determines that the theme is unknown and falls back to its default theme
 - react-monaco-editor invokes editorWillMount
 - my callback calls monaco.editor.defineTheme

An easy workaround here would be to load the monaco-editor scripts directly via e.g. `<script` in my app and then defining the theme prior to rendering react-monaco-editor. This, however, would remove from react-monaco-editor the responsibility of managing monaco-editor which I'd very much like to avoid. What I think I need to find is:

 - react-monaco-editor loads the monaco-editor scripts
 - _something_ invokes my callback which calls monaco.editor.defineTheme
 - react-monaco-editor invokes monaco.editor.create with my new theme's name
 - ~monaco determines that the theme is unknown and falls back to its default theme~

Any ideas?

**Comment by piotrpMSFT** [comment]
https://github.com/superRaytin/react-monaco-editor/blob/7f30d2311994265a14837a2c38c1ff8cc052fc23/src/index.js#L121

Looks like react-monaco-editor's editorWillMount gets called exactly where I'd like for it to... time for a new theory

**Comment by piotrpMSFT** [comment]
ok, found it. Bug on my side. I misused the editorOptions.theme property. For anyone else trying to do the same, the snippet above works just fine :)

**Comment by domoritz** [comment]
Thanks for posting the issue and your solution!
