### ISSUE TITLE
Multiple Files open at once

### ISSUE THREAD

**Issue by buddythumbs** [superRaytin/react-monaco-editor#67]
Hi - really cool library - good job!

Wondering if you could advise on how to achieve multiple files open at once? Like in the following image
![image](https://user-images.githubusercontent.com/24975408/32610531-feae6b2e-c55a-11e7-8528-432707929942.png)

Thanks

**Comment by domoritz** [comment]
That's beyond what monaco does. You'd have to implement your own tabs.

**Comment by TedDriggs** [comment]
@buddythumbs, the comment by @domoritz is correct from the UI perspective. However, you can use the `monaco.editor.IModel` interface to have Monaco track multiple open documents at once, each associated with a URI. Clicking a tab would then call `yourEditorInstance.setModel(...)`.

**Comment by danvoyce** [comment]
I solved this by doing the following...

`import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';`

and then in the options prop I created a model for each file:

```
options: {
        model:
          monaco.editor.getModel(monaco.Uri.parse(`file:///${name}.${ext}`)) ||
          monaco.editor.createModel(
            codeState[name],
            language,
            monaco.Uri.parse(`file:///${name}.${ext}`)
          ),
          ...
}
```
