### ISSUE TITLE
Can't resolve react-monaco-editor/diff 

### ISSUE THREAD

**Issue by lyudad** [superRaytin/react-monaco-editor#69]
1) npm i react-monaco-editor
2)
 ```
import MonacoDiffEditor from 'react-monaco-editor/diff';

   export const Component = () => (
             <MonacoDiffEditor
                width="800"
                height="600"
                language="javascript"
                original="hello"
                value="hello2"
    />
);
```
in editor, library already have red underline, after run I have same error :

> Can't resolve react-monaco-editor/diff

**Comment by expobrain** [comment]
Hi @lyudad,

the PR #70 fixes this issue by updating the documentation. You can solve your problem easily by importing `MonacoDiffEditor` from `react-monaco-editor/lib/diff`
