### ISSUE TITLE
vs/loader.js net::ERR_ABORTED error

### ISSUE THREAD

**Issue by stoplion** [superRaytin/react-monaco-editor#74]
Getting following error when using
`app.js:71814 GET http://localhost:9000/vs/loader.js net::ERR_ABORTED`

**Comment by miniprice** [comment]
@stoplion - Did you manage a fix for this?

**Comment by karenqinn** [comment]
> Getting following error when using
> `app.js:71814 GET http://localhost:9000/vs/loader.js net::ERR_ABORTED`

How did you fix this?

**Comment by imasif** [comment]
@stoplion How did you fix this?
