### ISSUE TITLE
Packing with electron?

### ISSUE THREAD

**Issue by buddythumbs** [superRaytin/react-monaco-editor#75]
Hi,

Love this library by the way!

I am using it with electron but for some reason when I package my app, none of the editors I have in my components load.

I am assuming this is something to do with my webpack config although I really have no idea.

For example my editor component looks like this:

```
import React, { Component } from 'react'
import styles from './Style.css'
import MonacoEditor from 'react-monaco-editor';
import moment from 'moment'
import { ipcRenderer } from 'electron'
import fs from 'fs'
import Loader from 'react-loaders'

export default class LogisticsEntry extends Component{
  constructor(props){
    super(props)
    this.state={
      code:"Start by typing 'record'"
    }
  }
  editorWillMount(monaco){
    const { locations } = this.props.logistics
    this.editor = monaco
    console.log(monaco.languages.getLanguages())
    if(!monaco.languages.getLanguages().mySpecialLanguage){
      // Register a new language
      monaco.languages.register({ id: 'mySpecialLanguage' });
      // Register a tokens provider for the language
      monaco.languages.setMonarchTokensProvider('mySpecialLanguage', {
        tokenizer: {
          root: [
            
          ]
        }
      });
      // Define a new theme that constains only rules that match this language
      monaco.editor.defineTheme('myCoolTheme', {
        base: 'vs',
        inherit: true,
        rules: [
          { token: 'custom-info', foreground: '808080' },
          { token: 'custom-error', foreground: 'ff0000', fontStyle: 'bold' },
          { token: 'custom-notice', foreground: 'FFA500' },
          { token: 'custom-date', foreground: '008800' },
        ]
      });
      // Register a completion item provider for the new language
      monaco.languages.registerCompletionItemProvider('mySpecialLanguage', {
        provideCompletionItems: () => {
          return [
            {
              label: 'record offline part',
              kind: monaco.languages.CompletionItemKind.Keyword,
              insertText: {
                value: [
                  '{',
                  '\tso\t\t\t: ${1: so number},',
                  '\tbid\t\t\t: ${2: barcode id},',
                  '\tlocation\t: ${3|'+locations+'|},',
                  '\},\n$0',
                ].join('\n')
              }
            }, {
              label: 'timestamp',
              kind: monaco.languages.CompletionItemKind.Keyword,
              insertText: {
                value: '|'+ moment().format('YYYY-MM-DD HH:mm') + '|\t${1:action}'
              }
            }
          ]
        }
      });
      monaco.languages.setLanguageConfiguration('mySpecialLanguage', {
        onEnterRules: [
          {
              beforeText: /[0-9]$/,
              action: {
                  indentAction: monaco.languages.IndentAction.None,
                  insertText: {
                    value: [
                      '{',
                      '\tso\t\t\t: ${1: so number},',
                      '\tbid\t\t\t: ${2: barcode id},',
                      '\tlocation\t: ${3|'+locations+'|},',
                      '\},\n$0',
                    ].join('\n')
                  }
              }
          }
        ]
      });
    }
  }
  editorDidMount(editor, monaco) {
    console.log('editorDidMount');
    editor.focus();
    ipcRenderer.on('open-file', (e,url)=> {
      fs.readFile(url, 'utf8', (err, data) => {
        if(err) console.error(err)
        console.log('input File:', data);
        this.setState({ code: data })
      })
    })
  }
  onChange(newValue, e) {
    this.setState({ code: newValue })
  }
  render() {
    const options = {
      selectOnLineNumbers: true
    };
    console.log(this)
    const code = this.state.code || ""
    return (
      <div className={styles.offline}>
        <h4>Offline Part Recording</h4>
        <MonacoEditor
            width="100%"
            height="300"
            language={'mySpecialLanguage'}
            theme='myCoolTheme'
            value={code}
            options={options}
            onChange={::this.onChange}
            editorDidMount={::this.editorDidMount}
            editorWillMount={::this.editorWillMount}
        />
      </div>
    );
  }
}
```
This renders like the following:

![image](https://user-images.githubusercontent.com/24975408/33718174-6da72728-db54-11e7-9d1b-cf851e7a206c.png)

but with no content...

Then the webpack copy code in the `webpack.config.main.prod,js` config:

```
import CopyWebpackPlugin from 'copy-webpack-plugin'
// for Monaco editor
    new CopyWebpackPlugin([
      {
        from: 'node_modules/monaco-editor/min/vs',
        to: 'vs',
      }
    ])
```

Then the webpack copy code in the `webpack.config.renderer.dev,js` config:

```
import CopyWebpackPlugin from 'copy-webpack-plugin'
// for Monaco editor
    new CopyWebpackPlugin([
      {
        from: 'node_modules/monaco-editor/min/vs',
        to: 'vs',
      }
    ])
```

Now I am not experienced enough to tell if this is something I can fix or not unfortunately!

Any help appreciated.

**Comment by domoritz** [comment]
Does https://github.com/superRaytin/react-monaco-editor/tree/master/examples/electron work for you?

**Comment by buddythumbs** [comment]
Hey - not sure how to apply it to my situation though.

So I've got a folder structure like the following:

```
├── CHANGELOG.md
├── LICENSE
├── README.md
├── app
├── appveyor.yml
├── dll
├── flow-typed
├── internals
├── node_modules
├── package-lock.json
├── package.json
├── release
├── resources
├── test
├── vbs
├── vs
├── webpack.config.base.js
├── webpack.config.eslint.js
├── webpack.config.main.prod.js
├── webpack.config.renderer.dev.dll.js
├── webpack.config.renderer.dev.js
├── webpack.config.renderer.prod.js
└── yarn.lock
```
The app folder is where the components live that use the `react-monaco-editor` 

So I have the following code in `webpack.config.main.prod.js, webpack.config.renderer.dev.js` and `webpack.config.renderer.prod.js`: 

```

import CopyWebpackPlugin from 'copy-webpack-plugin'


plugins:[
...
new CopyWebpackPlugin([
      {
        from: 'node_modules/monaco-editor/min/vs',
        to: 'vs',
      }
    ]),
...
]
```

```
├── app
│   ├── actions
│   │   └── editor.js <- dispatcher
│   ├── app.global.css
│   ├── app.html
│   ├── app.icns
│   ├── assets
│   │   ├── icons
│   │   ├── images
│   │   └── sounds
│   ├── components
│   │   └── Editor <-component using the react-monaco-editor
│   ├── containers
│   │   └── EditorPage.js <- page (used for react-router)
│   ├── dist
│   │   ├── 012cf6a10129e2275d79d6adac7f3b02.woff
│   │   ├── 448c34a56d699c29117adc64c43affeb.woff2
│   │   ├── 570eb83859dc23dd0eec423a49e147fe.woff2
│   │   ├── 674f50d287a8c48dc19ba404d20fe713.eot
│   │   ├── 89889688147bd7575d6327160d64e760.svg
│   │   ├── 912ec66d7572ff821749319396470bde.svg
│   │   ├── a37b0c01c0baf1888ca812cc0508f6e2.ttf
│   │   ├── af7ae505a9eed503f8b8e6982036873e.woff2
│   │   ├── b06871f281fee6b241d60582ae9369b9.ttf
│   │   ├── e18bbf611f2a2e43afc071aa2f4e1512.ttf
│   │   ├── e79bfd88537def476913f3ed52f4f4b3.eot
│   │   ├── f4769f9bdb7466be65088239c12046d1.eot
│   │   ├── fa2772327f55d8198301fdb8bcfc8158.woff
│   │   ├── fee66e712a8a08eef5805a46892932ad.woff
│   │   ├── renderer.prod.js
│   │   ├── renderer.prod.js.map
│   │   ├── style.css
│   │   └── style.css.map
│   ├── index.js
│   ├── main.dev.js
│   ├── main.prod.js
│   ├── main.prod.js.map
│   ├── menu.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── reducers
│   │   └── editor.js <- State
│   ├── routes.js
│   ├── store
│   │   ├── configureStore.dev.js
│   │   ├── configureStore.js
│   │   └── configureStore.prod.js
│   ├── utils
│   │   └── editor.js <- some utility functions
│   └── yarn.lock
```
What am I missing? Sorry for the newb questions (probably) but webpack is still sort of black box to me as I use the react-electron-boilerplate for this!

**Comment by buddythumbs** [comment]
Interestingly - when I package the app, the `vs` folder shows up in two places:

```
├── CHANGELOG.md
├── LICENSE
├── README.md
├── app
│   ├── actions
│   ├── app.global.css
│   ├── app.html
│   ├── app.icns
│   ├── assets
│   ├── components
│   ├── config
│   ├── containers
│   ├── data
│   ├── dist < - vs folder gets put in here also
│   ├── index.js
│   ├── main.dev.js
│   ├── main.prod.js
│   ├── main.prod.js.map
│   ├── menu.js
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── reducers
│   ├── routes.js
│   ├── store
│   ├── utils
│   └── yarn.lock
├── appveyor.yml
├── dll
│   ├── renderer.dev.dll.js
│   └── renderer.json
├── flow-typed
│   ├── module_vx.x.x.js
│   └── npm
├── internals
│   ├── flow
│   ├── img
│   ├── mocks
│   └── scripts
├── node_modules [1403 entries exceeds filelimit, not opening dir]
├── package-lock.json
├── package.json
├── release
│   ├── github
│   ├── latest-linux.yml
│   ├── latest-mac.yml
│   ├── linux-unpacked
│   ├── mac
│   └── win-unpacked
├── resources
│   ├── app-icon.icns
│   ├── icon.ico
│   ├── icon.png
│   └── icons
├── test
│   ├── actions
│   ├── components
│   ├── containers
│   ├── e2e
│   ├── example.js
│   ├── reducers
│   └── runTests.js
├── vbs
│   └── allStock.vbs
├── vs <- also gets put here
│   ├── base
│   ├── basic-languages
│   ├── editor
│   ├── language
│   └── loader.js
├── webpack.config.base.js
├── webpack.config.eslint.js
├── webpack.config.main.prod.js
├── webpack.config.renderer.dev.dll.js
├── webpack.config.renderer.dev.js
├── webpack.config.renderer.prod.js
└── yarn.lock
```

**Comment by jmrog** [comment]
For what it's worth, I'm having almost exactly the same issue at the moment, despite having followed the instructions in the documentation. My webpack setup is pretty complicated, however, which may have something to do with it. As in @buddythumbs' case, the CopyWebpackPlugin does put the `vs` folder inside of my `dist` folder (it doesn't also put it in my project's root folder), but that's apparently not enough for things to "just work."

**Comment by buddythumbs** [comment]
I guess the real question here seems to be, what is the relative path that the react-monaco-editor looks for the vs folder to be in?

**Comment by jmrog** [comment]
@buddythumbs Out of curiosity, does your webpack config include this bit of configuration (or maybe just the `__dirname` part)?

```
  node: {
    __dirname: false,
    __filename: false
  }
```

Mine does, so I'm wondering if perhaps that is causing odd behavior.

**Comment by buddythumbs** [comment]
No - not there at all in mine, but I’m not sure if that’s what’s screwing us if everything else is ok aside from this module??

**Comment by domoritz** [comment]
> I guess the real question here seems to be, what is the relative path that the react-monaco-editor looks for the vs folder to be in?

Is there an error in the console for the 404s?

**Comment by buddythumbs** [comment]
Yes so I am getting 404's now actually when I debug production code:
![image](https://user-images.githubusercontent.com/24975408/33795147-584b037e-dcd3-11e7-827a-a2ab273b6b66.png)
![image](https://user-images.githubusercontent.com/24975408/33795253-e429563c-dcd5-11e7-975d-edfc3615aeb5.png)



So with this in mind,- I probably need to change a relative path somewhere right?

I think I have a few balls in the air here which I need to sort out.

First of all, I am using the boilerplate from here https://github.com/chentsulin/electron-react-boilerplate 
which has no less than 6 `webpack.config.*` files! 

When I put the code from the docs in the `webpack.config.base.js` I get a vs folder in two places, first is on same level as `app/` and one in `app/dist/`

I don't understand the webpack file in the electron example - maybe if someone could explain what each bit does then I might be able to see if I am doing something wrong (especially seeing as I don't have some of the lines in my code)

**Comment by domoritz** [comment]
Have you seen the note in https://github.com/superRaytin/react-monaco-editor/pull/72?

**Comment by buddythumbs** [comment]
About the `<base ref="/" />` ? Yes I am looking at it but unsure where exactly that goes?

**Comment by domoritz** [comment]
You can put that in your html files. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by buddythumbs** [comment]
Excellent!!

I've got it working!! 

So I added `<base href={location.pathname} />` to the head tag of my page and it works!

So just as an FYI the following is how I have it working.

From nested component `app/componentes/logbook/logbook.js` I have the code from readme.

Then in my `webpack.config.base` file I put the `copy-webpack-plugin` code from the readme.

So I think my issue was the `react-router` messing with the relative paths? 

Anyway it seems to be fixed now!!
Thanks!

**Comment by jmrog** [comment]
For what it's worth, adding the `<base>` element did not fix things for me. I finally did get things working, but here is what I had to do:

1. Delete [this line](https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L77).
2. Change [this line](https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L86) so that it looks like this:

```javascript
const monacoPath = 'node_modules/monaco-editor/min';
```

3. Add this element in the `<head>` section of the `index.html` file that is loaded by Electron:

```html
<link rel="stylesheet" data-name="vs/editor/editor.main" href="vs/editor/editor.main.css">
```

My setup is probably very customized/specific, so I'm not sure whether this will be helpful to anyone else. I am using webpack-dev-server in addition to webpack itself, React, and Electron.

**Comment by domoritz** [comment]
Any siuggestions for how we could improve the code here to make this more robust?

**Comment by jmrog** [comment]
In my particular case (again, my case is probably very specific), there are a few things that would have helped me:

1. Users can currently specify the `loaderUrl` using `requireConfig.url`, but only if they are _not_ using Electron. In other words, I couldn't set the loaderUrl for myself because the code currently overrides whatever I provide if `inElectron` is true. See [here](https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L71-L78).

2. There was no way for me to override the Monaco path in Electron, and I needed to do that.

I could submit a very small PR allowing these overrides if that would make the issue clearer.
