### ISSUE TITLE
set language after editorWillMount

### ISSUE THREAD

**Issue by lyudad** [superRaytin/react-monaco-editor#77]
I don't know which file will be opened. So I can't set language as props

```
 <MonacoEditor
            width="700px"
            height="700px"
            language={this.getLanguage(content)}
            value={value}
            options={editorOptions}
            onChange={this.onChange}
            editorDidMount={this.editorDidMount}
/>
```

this.getLanguage method return language if monaco exist (used monaco.languages.getLanguages() ), but if file was opened first time, monaco is underfined so I cant get language. Is there any oportunity to set language after editorWillMount function?

**Comment by expobrain** [comment]
What about if `this.getLanguage()` returns a default language if the editor is `undefined`? 

In this way you'll always a language set: a default one when the editor is not set yet and the correct one once the editor is loaded.

**Comment by lyudad** [comment]
Sure, I set default language. if no language, this.getLanguage return simple text, but I want add delta Decorations, which need language parameter. And also in this case text have no colors, but if I open `js` file, for example, I want see colors like `js` file should look
