### ISSUE TITLE
delete code manualy

### ISSUE THREAD

**Issue by lyudad** [superRaytin/react-monaco-editor#82]
"react-monaco-editor": "^0.13.0"

I need delete some code, if user click on button. I think, because onChange event for editor not work, I can't use `ctl+z` / `command+z` for return code (return deleted code). If I understand right this this because my new value not in variable this.__current_value  https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L51 
I can't find way to trigger on change event after my onClick event. Is there any way to do it ?

**Comment by expobrain** [comment]
I just checked and indeed the `onChange` callback is correctly called on every change of the content of the editor. 

You can keep a copy of the last `onClick` callback arguments and when the user click on button you can set back che previous content of the editor by one of the two ways https://github.com/superRaytin/react-monaco-editor/blob/master/examples/browser/index.js#L27-L35 for updates.

This if I understood correctly your question :-)

**Comment by expobrain** [comment]
Close for inactivity, feel free to reopen
