### ISSUE TITLE
How to registerCompletionItemProvider (and avoid duplicates)?

### ISSUE THREAD

**Issue by nickaversano** [superRaytin/react-monaco-editor#88]
Right now, I'm calling `monaco.languages.registerCompletionItemProvider` in the `editorDidMount` method. How would I prevent adding multiple completion providers if this component continuously gets mounted and unmounted? It doesn't appear that monaco provides a `unregister` method and editor.dispose doesn't remove additions made to monaco.languages

**Comment by nickaversano** [comment]
nevermind, answered my own question. `registerCompletionItemProvider` returns an `IDisposable` with the `dispose` method which I can call on unmount

**Comment by JeremyRippert** [comment]
Hello @nickav , I ran into the same issue about registerCompletionItemProvider creating duplicates of my suggestions. However, I tried saving the IDisposable into a variable and using dispose() on unmount, without success.

Here is my code : 

`  const [completionDisposable, setCompletionDisposable] = useState({});

  useEffect(
    () => () => {
      completionDisposable.dispose();
    },
    [],
  );

  const editorWillMount = (monaco: any) => {
    setMonacoObject(monaco);
    setCompletionDisposable(
      monaco.languages.registerCompletionItemProvider('vb', {
        provideCompletionItems() {
          return {
            suggestions: createAutoComplete(parameterList),
          };
        },
      }),
    );
  };` 

I get an error `TypeError: completionDisposable.dispose is not a function` anytime I leave the page.

Do you remember how you managed to dispose of the completionItemProvider ? 
Thanks in advance

**Comment by nickav** [comment]
@JeremyRippert I don't think you're using effects correctly here. They are confusing to be honest. I thought the idea was that the effect is supposed to return a function to destroy it.

**Comment by PunKHS** [comment]
Hello @nickav, if is possible, please attach some example, how to use `dispose()` method

**Comment by PunKHS** [comment]
Answer:
```
private editor: any

editorDidMount = (editor: monacoEditor.editor.IStandaloneCodeEditor) => {
const { suggestions } = this.props;
this.editor = monacoEditor.languages.registerCompletionItemProvider('myLang', {
    provideCompletionItems: () => { return { suggestions: this.getSuggestions(suggestions) } },
});
}

componentWillUnmount = () => {
    this.editor && this.editor.dispose();
}
```

**Comment by tavisca-ysant** [comment]
@nickav . Please help with this

**Comment by pk091990** [comment]
Hi @PunKHS and @rbalet

I'm facing the same duplicate issue on registerCompletionItemProvider. Using monaco-editor@0.14.3 with SPFX 1.11.
I'm disposing the editor on componentWillUnmount as suggested but not working for me.
![image](https://user-images.githubusercontent.com/46436213/90645236-5685e580-e253-11ea-906b-f5300fb224df.png)

I'm calling registerCompletionItemProvider on button click, Also tried with latest monaco-editor@0.20.0 but its throwing error on building the solution with SPFX 1.11. Can you tell me what I'm missing here.

**Comment by HEBOS** [comment]
private completionItemProvider: monaco.IDisposable;

someFunc() {
if (!!this.completionItemProvider)
      this.completionItemProvider.dispose();
    
      this.completionItemProvider = monaco.languages.registerCompletionItemProvider(
	  ...
}

**Comment by yeikel** [comment]
@HEBOS Thank you!

**Comment by dkozar** [comment]
>```js
> useEffect(
>     () => () => {
>       completionDisposable.dispose();
>     },
>     [],
>);
> ```

It seems you're not RETURNING the destructor. This should work:

```js
useEffect(
    () => {
        // initialization on mount here...
        
        // returning the destructor
        return completionDisposable.dispose;
    },
    [],
);
```

If no initialization, it's even simpler:

```js
useEffect(
    () => completionDisposable.dispose,
    [],
);
```

**Comment by dkozar** [comment]
> I get an error TypeError: completionDisposable.dispose is not a function anytime I leave the page.

That's because `completionDisposable `isn't a dependency of `useEffect`. At the time of running the `useEffect` it was `{}` (as set at the beginning), and it stayed like that even after it has been set.

```js
useEffect(
    () => completionDisposable.dispose,
    [completionDisposable], // dependencies
);

```

**Comment by love1119** [comment]
This should work.

`useEffect(() => {
    return () => {
      if (typeof completionDisposable.dispose === "function") {
        completionDisposable.dispose();
      }
    };
  }, [completionDisposable]);`

**Comment by zaowang-ms** [comment]
Thanks for the discussion, it helped me a lot
