### ISSUE TITLE
json automatic formatting

### ISSUE THREAD

**Issue by stxwd46** [superRaytin/react-monaco-editor#89]
#### problem 
I used JSON.stringif to format the json, and set it to the ```value``` property, but it will not auto format document. How can i do  to resolve this problem?

#### code
```js
const value = '{"a": "1", "b": "2"}';
<MonacoEditor
    width="800"
    height="600"
    value={value}
/>
```

#### result 
![image](https://user-images.githubusercontent.com/7361933/35263060-28f8274e-0052-11e8-88b7-a2b641980a12.png)

#### expected result;
![image](https://user-images.githubusercontent.com/7361933/35263100-62962b5e-0052-11e8-8758-9dcb98df69e4.png)

**Comment by domoritz** [comment]
You can right click -> format JSON in the editor.

**Comment by stxwd46** [comment]
@domoritz right click to format the json is manually formatting, not automatic formatting.

finally I resolve this problem by this way.
```js
editorDidMount(editor, monaco) {
    setTimeout(function() {
      editor.getAction('editor.action.formatDocument').run();
    }, 300);
 }
```
however， I don't know why it have no effect when I get rid of ```setTimeout```

**Comment by domoritz** [comment]
Hmm, what happens if you set the timeout to 0?

**Comment by stxwd46** [comment]
It will not format automatic.
for example, my initial value of ```schema``` is ```'{}'```. And I will get its real data by a asynchronous request.
```js
componentWillMount() {
    // get the real data of this.props.schema
    this.props.dispatch({
        type: 'app/getApp'
    });
}

editorDidMount(editor, monaco) {
    setTimeout(function() {
      editor.getAction('editor.action.formatDocument').run();
    }, 300);
}

render () {
    <MonacoEditor
        width="800"
        height="800"
        language="json"
        value={this.props.schema}
        editorDidMount={this.editorDidMount.bind(this)}
    />
}
```
Let us suppose that the real data of ```schema``` is ```'{"a": "1", "b": "2"}'```
if I set the timeout to 0, it will not format automatic like this
![image](https://user-images.githubusercontent.com/7361933/35320681-9c4a06ae-011f-11e8-896d-7fb7df7b31c9.png)

when I set the timeout to 300m, it will take effect like this
![image](https://user-images.githubusercontent.com/7361933/35320715-b6810e00-011f-11e8-9bdf-dc361a7a1df1.png)

**Comment by domoritz** [comment]
Can you set the value to (including newlines)?

```
{
  "foo": "bar"
}
```

**Comment by stxwd46** [comment]
That is another way to resolve this problem.
But I think the best way is like the API ```formatOnPast```, when you set the data to the ```value``` property, it can format automatic :)

**Comment by stxwd46** [comment]
That is another way to resolve this problem.
But I think the best way is like the API formatOnPaste, when you set the data to the value property, it can format automatic :)

**Comment by stxwd46** [comment]
That is another way to resolve this problem.
But I think the best way is like the API ```formatOnPaste```, when you set the data to the ```value``` property, it can format automatic :)

**Comment by daisybaicai** [comment]
you can format string,
like this: 

```javascript
export function formatJSON(val = {}) {
  try {
    const res = JSON.parse(val);
    return JSON.stringify(res, null, 2)
  } catch {
    const errorJson = {
      "error": `非法返回${val}`
    }
    return JSON.stringify(errorJson, null, 2)
  }
}
```


```javascript
const data = `{"a": "1", "b": "2"}`;

        <MonacoEditor
          width="654"
          height="329"
          language="json"
          theme="vs-light"
          value={formatJSON(data)}
          options={options}
        />
```

**Comment by charanjit-mtech** [comment]
What if there's other language?

**Comment by jMohammdi** [comment]
> @domoritz right click to format the json is manually formatting, not automatic formatting.
> 
> finally I resolve this problem by this way.
> 
> ```js
> editorDidMount(editor, monaco) {
>     setTimeout(function() {
>       editor.getAction('editor.action.formatDocument').run();
>     }, 300);
>  }
> ```
> 
> however， I don't know why it have no effect when I get rid of `setTimeout`

✅ but in this case, your data in the editor Monaco  is not readOnly it's my problem

**Comment by gotoreadyai** [comment]
> Hmm, what happens if you set the timeout to 0?

what do you think, master?
