### ISSUE TITLE
Is not working...

### ISSUE THREAD

**Issue by BrunoQuaresma** [superRaytin/react-monaco-editor#91]
I follow the current tutorial but the editor not works... :cry:

**Comment by domoritz** [comment]
Please be more specific. Try the example first.

**Comment by BrunoQuaresma** [comment]
@domoritz I try the README example. The first error that I notice was that the require scripts are unavaiable (404). After fix that the console display `Unexpected token <`

**Comment by domoritz** [comment]
Try https://github.com/superRaytin/react-monaco-editor/tree/master/examples
