### ISSUE TITLE
Add className prop

### ISSUE THREAD

**Issue by TedDriggs** [superRaytin/react-monaco-editor#93]
Right now, styling the editor container requires knowing `react-monaco-editor-container` as the magic class name for the element. This makes it difficult for someone to apply styles to the container in a clean and modular way.

# Request
1. Expose an optional `className` prop
1. When defined, the emitted `<div />` includes both `react-monaco-editor-container ${this.props.className}`

**Comment by domoritz** [comment]
Can't you just wrap the element in another div with a class? 

Are there other components that expose className? If so, I'm happy to accept a PR.

**Comment by TedDriggs** [comment]
> Can't you just wrap the element in another div with a class?

I'll try that. My team started exposing the prop when intermediate container elements made sizing difficult, for a variety of reasons.

**Comment by TedDriggs** [comment]
That worked wonders.
